"""
Divergence computation utilities for entropy estimation in flow matching models.

This module provides utilities to compute the divergence of velocity fields,
which is used to estimate the entropy of distributions generated by flow matching:

    H(p_1) = H(p_0) + ∫_0^1 E_{p_t}[∇·v_θ(x_t, t)] dt

References:
    - Hutchinson's trace estimator: https://openreview.net/forum?id=PqvMRDCJT9t
    - Flow matching divergence alignment: https://openreview.net/forum?id=PqvMRDCJT9t
"""

from typing import Optional

import torch
from torch import Tensor


def divergence_exact(v_func, x: Tensor, t: Tensor) -> Tensor:
    """Compute exact trace of Jacobian for low-dimensional cases (e.g., 2D).

    This function computes the exact divergence ∇·v by calculating the trace
    of the Jacobian matrix of the velocity field v with respect to x.

    Args:
        v_func: Velocity function that takes (x, t) and returns velocity (B, D)
        x: Input positions (B, D) where B is batch size, D is dimension
        t: Time values (B,) or (B, 1)

    Returns:
        Tensor: Divergence values (B,), one per sample in the batch

    Example:
        >>> flow = lambda x, t: model(x_t=x, t=t)
        >>> x = torch.randn(32, 2, requires_grad=True)
        >>> t = torch.full((32,), 0.5)
        >>> div = divergence_exact(flow, x, t)
        >>> div.shape
        torch.Size([32])
    """
    with torch.enable_grad():
        x = x.detach().requires_grad_(True)
        v = v_func(x, t)  # (B, D)

        div_terms = []
        for d in range(v.shape[1]):
            # Compute ∂v_d/∂x_d
            grad_vd = torch.autograd.grad(
                v[:, d].sum(), x, create_graph=True, retain_graph=True
            )[0][:, d]
            div_terms.append(grad_vd)

        result = torch.stack(div_terms, dim=1).sum(dim=1)  # (B,)

    return result.detach()


@torch.no_grad()
def hutchinson_divergence(v_func, x: Tensor, t: Tensor, n_probe: int = 1) -> Tensor:
    """Hutchinson's trace estimator for high-dimensional divergence (e.g., images).

    This is an unbiased estimator of the trace of the Jacobian using random probe vectors.
    The estimator is E[z^T (∇v) z] where z ~ N(0, I) or Rademacher distribution.

    For training-time use with backpropagation, remove @torch.no_grad() decorator
    and pass create_graph=True to the grad call.

    Args:
        v_func: Velocity function that takes (x, t) and returns velocity
        x: Input positions (B, ...) where B is batch size
        t: Time values (B,) or (B, 1)
        n_probe: Number of probe vectors for variance reduction (default: 1)

    Returns:
        Tensor: Estimated divergence values (B,), one per sample in the batch

    Example:
        >>> flow = lambda x, t: model(x=x, t=t)
        >>> x = torch.randn(16, 3, 32, 32)  # CIFAR-10 batch
        >>> t = torch.full((16,), 0.5)
        >>> div = hutchinson_divergence(flow, x, t, n_probe=2)
        >>> div.shape
        torch.Size([16])

    Note:
        - n_probe=1-4 usually provides good variance/cost tradeoff
        - Higher n_probe reduces variance but increases computation
        - For sampling (no grad needed), use @torch.no_grad() (default)
        - For training, remove @torch.no_grad() and set create_graph=True
    """
    div_est = torch.zeros(x.size(0), device=x.device)

    for _ in range(n_probe):
        # Use Rademacher distribution for probe vectors (more efficient than Gaussian)
        eps = torch.randn_like(x)
        eps = eps / (eps.norm(dim=tuple(range(1, eps.ndim)), keepdim=True) + 1e-8)

        # We need gradients for the Hutchinson estimator
        with torch.enable_grad():
            x_copy = x.detach().requires_grad_(True)
            v = v_func(x_copy, t)

            # Compute v^T ε (Pearlmutter trick)
            v_eps = (v * eps).sum()

            # Compute ∇(v^T ε) · ε = trace estimate
            grad_v_eps = torch.autograd.grad(
                v_eps, x_copy, create_graph=False, retain_graph=False
            )[0]

            div_contribution = (grad_v_eps * eps).view(x.size(0), -1).sum(dim=1)
            div_est = div_est + div_contribution

    return div_est / float(n_probe)


def compute_entropy_from_divergence(
    divergence_values: list[Tensor],
    time_steps: Tensor,
    base_entropy: Optional[float] = None,
    dim: Optional[int] = None,
) -> Tensor:
    """Integrate divergence over time to compute entropy estimate.

    Uses trapezoidal rule to integrate the expected divergence:
        H(p_1) = H(p_0) + ∫_0^1 E[∇·v_θ(x_t, t)] dt

    Args:
        divergence_values: List of divergence tensors (B,) at each time step
        time_steps: Time values (T,) corresponding to divergence_values
        base_entropy: Entropy of base distribution H(p_0). If None, computed from dim
        dim: Dimensionality for computing H(p_0) for standard Gaussian base.
             Only used if base_entropy is None

    Returns:
        Tensor: Entropy estimate H(p_1)

    Example:
        >>> div_vals = [torch.tensor([0.1, 0.2]), torch.tensor([0.15, 0.25])]
        >>> times = torch.tensor([0.0, 1.0])
        >>> H = compute_entropy_from_divergence(div_vals, times, dim=2)
    """
    if base_entropy is None:
        if dim is None:
            raise ValueError("Either base_entropy or dim must be provided")
        # H(p_0) for standard Gaussian in D dimensions: 0.5 * D * (1 + log(2π))
        base_entropy = 0.5 * dim * (1.0 + torch.log(torch.tensor(2.0 * 3.141592653589793)))

    # Trapezoidal integration
    entropy_integral = 0.0
    for i in range(len(divergence_values) - 1):
        dt = time_steps[i + 1] - time_steps[i]
        # Average divergence over batch, then integrate
        avg_div_current = divergence_values[i].mean()
        avg_div_next = divergence_values[i + 1].mean()
        entropy_integral += 0.5 * (avg_div_current + avg_div_next) * dt

    return base_entropy + entropy_integral
